### ISSUE TITLE
The question of reproduce.exe

### ISSUE THREAD

**Issue by erqihuang** [tastiSaher/SpectralReconstruction#2]
The outstanding performance of this work is amazing. However, the reproduce.exe cannot process multi RGB images in the Win10 simultaneously. Though the images_real contains several images, the folder of result only has a pair of .mat/.npy files. Could you guys provide usages of multi images process?
![image](https://user-images.githubusercontent.com/38005430/140285735-6645a480-33a6-4f7d-bb8a-e65a8cddaf0c.png)

**Comment by tastiSaher** [comment]
Thank you for your interest in our work. I just checked and it turns out that the code implicitly assumes that the image files are named in a certain way (like it was done in the NTIRE2018 challenge).

The way i see it, you have two options to run our code on your files:
1. If you want to use the executable with multiple files, rename your image files according to the challenge convention. Supported file formats are *.png and *.jpg. Hereby, png files should be named BGU_HS_XXXXX_clean.png and jpg files BGU_HS_XXXXX_camera.jpg (replace the X with whatever you like). 
2. If running the python script directly is an option for you, i fixed reproduce.py to handle general image names. I would especially recommend this option if you intend to process a lot of images, since only via the script, gpu support is possible. Processing will thus become a matter of seconds.

**Comment by erqihuang** [comment]
Thank you for your reply.  The updated python scripts have addressed this problem.
